# Generated by Django 5.2.12 on 2026-03-12 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Photographer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pexels_id", models.IntegerField(unique=True)),
                ("name", models.CharField(max_length=255)),
                ("url", models.URLField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pexels_id", models.IntegerField(unique=True)),
                ("width", models.PositiveIntegerField()),
                ("height", models.PositiveIntegerField()),
                ("url", models.URLField(max_length=500)),
                ("alt", models.TextField(blank=True, default="")),
                ("avg_color", models.CharField(blank=True, default="", max_length=7)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "photographer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="photos.photographer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PhotoSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("size_label", models.CharField(max_length=20)),
                ("url", models.URLField(max_length=500)),
                (
                    "photo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sources",
                        to="photos.photo",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="photo",
            index=models.Index(
                fields=["photographer"], name="photos_phot_photogr_9f9a21_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="photo",
            index=models.Index(
                fields=["created_at"], name="photos_phot_created_84134a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="photo",
            index=models.Index(
                fields=["pexels_id"], name="photos_phot_pexels__a46ae3_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="photosource",
            constraint=models.UniqueConstraint(
                fields=("photo", "size_label"), name="unique_photo_size_label"
            ),
        ),
    ]
